# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAeONoCsv7U_LDQaeuO6dnXN5F8YFxLT

app.py
"""

app_code = """
import streamlit as st
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image

# Load saved model
model = load_model("pneumonia_cnn_model.h5")
class_labels = ['Normal', 'Pneumonia']

st.title("Pneumonia Detection from Chest X-ray")
st.write("Upload a chest X-ray image and the model will predict whether it's Normal or Pneumonia.")

uploaded_file = st.file_uploader("Choose an X-ray image", type=["jpg","jpeg","png"])

if uploaded_file is not None:
    img = Image.open(uploaded_file).convert("L")
    st.image(img, caption="Uploaded Image", use_column_width=True)

    # Preprocess image
    img = img.resize((150,150))
    img_array = np.array(img)/255.0
    img_array = np.expand_dims(img_array, axis=(0,-1))  # shape: (1,150,150,1)

    # Prediction
    prediction = model.predict(img_array)[0][0]
    predicted_label = class_labels[int(prediction > 0.5)]
    probability = prediction if prediction > 0.5 else 1 - prediction

    st.success(f"Prediction: {predicted_label}")
    st.info(f"Probability: {probability:.2f}")
"""

# Save app.py
with open("app.py", "w") as f:
    f.write(app_code)